version: '3.8'

services:
  web:
    image: python:3.9  # Python imajı örneği
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  db:
    image: busybox  # SQLite için imaj kullanmanıza gerek yok
    volumes:
      - db_data:/data

volumes:
  db_data: