# Generated by Django 4.2.4 on 2023-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huseyinweb", "0002_alter_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
    ]
