# Generated by Django 4.2.4 on 2023-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huseyinweb", "0003_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("message", models.TextField()),
            ],
        ),
    ]
