# Generated by Django 4.2.4 on 2023-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huseyinweb", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.IntegerField(choices=[(1, "New"), (2, "Read")], default=1),
        ),
    ]
