# Generated by Django 4.2.4 on 2023-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huseyinweb", "0006_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("message", models.TextField()),
            ],
        ),
    ]
