apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mainapp-web
  template:
    metadata:
      labels:
        app: mainapp-web
    spec:
      containers:
        - name: mainapp-web
          image: huseyinurak/mainapp-web:latest
          ports: 
          - containerPort: 8000